#- name: Install composer on {{ project_name }}
#  composer: command=install working_dir=/opt/fcb/{{ project_name }}

# Set up project database
- name: Create database {{ database }}
  mysql_db: name={{ database }} state=present

- name: Create user and password for dbs on localhost
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} host=localhost priv=*.*:ALL,GRANT state=present

- name: Create user and password for dbs on % host
  mysql_user: name={{ mysql_user }} password={{ mysql_password }} host=% priv=*.*:ALL,GRANT state=present

#- name: Copy master sqls
#  copy: src=../../../../scripts/sql/{{item}} dest=/tmp/{{ item }}
#  with_items: "{{ master_db_sql }}"

#- name: excute master sql scritps  to {{ database }}
#  mysql_db: name={{ database }} state=import target=/tmp/{{ item }}
#  with_items: "{{ master_db_sql }}"

# Set up prject Vitual host
- name: vhost dev.vf.com.pe
  template: src=dev.vf.com.pe.conf dest=/etc/httpd/conf.d/
  notify:
       - restart httpd
#       - restart memcache

- name: host file | update host file
  lineinfile: "dest=/etc/hosts
    insertafter=EOF
    line='127.0.0.1  dev.vf.com.pe'
    regexp='127.0.0.1  dev.vf.com.pe'
    state=present"
  notify:
     - restart httpd
#     - restart memcache

# Set Up project configuration
#- name: Create vhosts cp Data Directories
#  file: path=/opt/ts/{{ project_name }}/data/{{item}} state=directory owner=root mode=0777
#  with_items:
#     - cache
#     - log

#- name: Copy local cp config file
#  copy: src={{item}} dest=/root/{{item}} owner=vagrant
#  with_items:
#     - local.php

#- command: mv -f /root/local.php /opt/ts/{{ project_name }}/config/autoload/
